apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-demo.fullname" . }}
  labels:
    {{- include "account-demo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "account-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "account-demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "account-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.application.port.name }}
              containerPort: {{ .Values.application.port.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Chart.Name }}-config-volume
              mountPath: {{ .Values.application.volume.mountPath }}
          envFrom:
            - configMapRef:
                name: {{ .Values.application.env.configMapRef }}
            - secretRef:
                name: {{ .Values.application.env.secretRef }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.application.port.name }}
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.application.port.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            name: {{ .Chart.Name }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
